name: 'PlayerManager'
version: '1.0'
main: 'io.github.kuroka3.playermanager.PlayerManager'
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.21
  - org.jetbrains.kotlin:kotlin-reflect:1.7.21
  - io.github.monun:kommand-core:3.1.6
  - io.github.monun:tap-core:4.9.3

permissions:
  playermanager.ban:
    description: Ban Player Permission
    default: false
  playermanager.warn:
    description: Warn Player Permission
    default: false
  playermanager.mute:
    description: Mute Player Permission
    default: false
  playermanager.kick:
    description: Kick Player Permission
    default: false
  playermanager.managecase:
    description: Manage Case Reason Permission
    default: false