name: 'PlayerManagerKotlin'
version: '${version}'
main: 'io.github.kuroka3.playermanagerkotlin.PlayerManagerKotlin'
api-version: '${paperVersion}'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}
  - io.github.monun:kommand-core:3.1.6
  - io.github.monun:tap-core:4.9.3

permissions:
  playermanager.ban:
    description: asdf